### ISSUE TITLE
Multiverse inventories

### ISSUE THREAD

**Issue by Bobbbe** [BentoBoxWorld/InvSwitcher#1]
Spigot 1.13.2
java 8
database: yaml

1- The plugin "Multiverse Inventories" is not compatible, after several attempts, there is always a part of the inventory that is not shared and also money.
I tried to remove the "addon invswitcher" and everything is sharing well without this addon, but the addon is useful and essential for the challenge and the bentobox, so I put everything back in place and the sharing problem came back .

I have removed the "Multiverse Inventory" plug-in for the moment but without a sharing of inventories and money, it is impossible to create any other map that could be combined with the BSB maps.
Example. a map named at our choice that would serve as the point of arrival before choosing which map we want to go to, BAB or AcidIsland.

**Comment by tastybento** [comment]
Inv switcher is completely optional and not essential if you already have another plugin that performs the same job. Don’t try to run two at the same time.

**Comment by Bobbbe** [comment]
I tried not to install the invswitcher addon, but if I reset an island without the invswitcher, it reset all the inventories of BSB and AcidIsland even if I use the multiverse inventories!
If I do not reset and I use the multiverse inventories, everything is fine and everything is well shared.

**Comment by Ironic8b498** [comment]
I have noticed I lose my inventory sometimes on server reboot, on Acid Island, SkyBlock and the main world I use as a lobby

**Comment by tastybento** [comment]
@Ironic8b498 Is this another bug? If so, please file a separate report and let me know your environment.
