### ISSUE TITLE
Inventory issue on version 1.16.1

### ISSUE THREAD

**Issue by DraimCiDo** [BentoBoxWorld/InvSwitcher#11]
when you switch from gamemode to gamemode, and you enter the chest, then you have things from the previous regime.

Addons: 
![image](https://user-images.githubusercontent.com/53317146/88157480-7ce44100-cc13-11ea-9964-4c6a2327c14e.png)

Version and Plugins: 
![image](https://user-images.githubusercontent.com/53317146/88157635-aef5a300-cc13-11ea-80e3-f3651d310e04.png)

**Comment by tastybento** [comment]
I am running on 1.16.1 and I cannot replicate this on Paper or Spigot. If I am in AcidIsland and do /island to go to BSkyBlock, my inventory changes immediately.

You wrote:
> when you switch from gamemode to gamemode, and you enter the chest, then you have things from the previous regime.

Please give step by step instructions on how to cause the problem.

I do not understand what you mean by "enter the chest".

**Comment by DraimCiDo** [comment]
The bug has been resolved. The problem was in the "Purpur" server core

UPD: The same problem was on "Tuinity"

> Please give step by step instructions on how to cause the problem.

The problem was, when you enter different worlds, you always have the same inventory.

**Comment by DraimCiDo** [comment]
> Please give step by step instructions on how to cause the problem.

The problem was, when you enter different worlds, you always have the same inventory.

**Comment by tastybento** [comment]
Okay!
