### ISSUE TITLE
Advancement notifications

### ISSUE THREAD

**Issue by BONNe** [BentoBoxWorld/InvSwitcher#12]
#### Describe the bug

When player switch gamemodes, server get notified with about new advancements, however, it just adds advancements which are in gamemode. So rapidly switching gamemodes just spams the whole server with advancement unlock messages.

#### Steps to reproduce the behavior

Get some advancements in one gamemode, while different ones in another gamemode.
Then switch gamemodes.

#### Expected behavior

The server should not be notified about unlocked advancements if the player switches game modes and it is just restoring advancements for a given game mode.

#### Screenshots and videos (Optional)

![bug](https://user-images.githubusercontent.com/1344358/107784008-9d145280-6d53-11eb-8d03-ff973bd512f9.png)

##### Output of `/bbox version` (Mandatory)

![version](https://user-images.githubusercontent.com/1344358/107784042-a7cee780-6d53-11eb-9c2a-e5b1a8e7d971.png)
 
### Additional context (Optional)

Tested on tastybento server.

**Comment by tastybento** [comment]
There is a gamerule that turns off advancement announcements. This is the simplest way to prevent the spamming and I expect most real servers have this switched off anyway. I am not sure that it's possible to prevent the server announcement via Bukkit API. Any ideas?
