### ISSUE TITLE
InvSwitcher

### ISSUE THREAD

**Issue by Davidas59** [BentoBoxWorld/InvSwitcher#26]
### Expected behavior

Players teleport to Skyblock and then return to the world, and items disappear.

### Observed/Actual behavior

i don't know

### Steps/models to reproduce

i don't know

### BentoBox version

1.24.1

### Plugin list

![Screenshot_90](https://github.com/BentoBoxWorld/InvSwitcher/assets/26489219/399fd55a-eb90-4d1d-a7e1-2ee1725579d7)

### Other

Players teleport to Skyblock and then return to the world, and items disappear.
 and money disappear world

**Comment by tastybento** [comment]
InvSwitcher does not touch money so I am not sure why you are seeing that.

Can you share a video of this happening?

What plugins do you have? Maybe there is another plugin doing something similar.

**Comment by Davidas59** [comment]
I can't show it because sometimes it works well and sometimes items disappear.

**Comment by Davidas59** [comment]
I was told to write it report

**Comment by tastybento** [comment]
What plugins do you have?

**Comment by Davidas59** [comment]
server plugins or bbox?

**Comment by Davidas59** [comment]
BentoBox?

**Comment by tastybento** [comment]
Server plugins. Run `/plugins` and share.

**Comment by Davidas59** [comment]
![Screenshot_94](https://github.com/BentoBoxWorld/InvSwitcher/assets/26489219/5f0b8873-4915-40de-a045-e7d8e06b3fcf)

ny server plugins

**Comment by Davidas59** [comment]
how to fix bug?

**Comment by tastybento** [comment]
I see you are using Multiworldmoney, which may account for the money problem. I did write that plugin but I haven't worked on it for years, so maybe that is having issues. This would not affect items disappearing though. 
However, in general I don't have enough information to fix. I would need some repeatable way to make the problem happen but it sounds like it is random for you. If you find a way to replicate it, let me know.

**Comment by Davidas59** [comment]
i found bug, Video :https://imgur.com/6WwcABs

Multiworldmoney: that the money is separate

**Comment by tastybento** [comment]
Were there any errors reported in the console when you logged out? Or when you logged back in?
Also, please run `/bbox v` and share the output.

**Comment by Davidas59** [comment]
![Screenshot_97](https://github.com/BentoBoxWorld/InvSwitcher/assets/26489219/3cc32893-0f4d-4aa5-a402-8b10fa4ab6e0)

can't find anything problem console.

**Comment by Davidas59** [comment]
bug again video: https://imgur.com/8sj7iT2

**Comment by tastybento** [comment]
In that latest video it doesn't look like InvSwitcher was actually doing anything. You had 32 dirt at spawn, then you went to SkyBlock world (I assume spawn and SB are different worlds) but you kept the 32 dirt. Then you picked up extra items, logged out, back in, still had the inventory - no bug there, but then went to spawn and kept everything. 

So, yeah, it's not working. I still think another plugin is causing the issue. If you run only BentoBox, like on your own PC/test server, does this happen?

**Comment by Davidas59** [comment]
It still doesn't make sense. You start in the world with items, then you move to Skyblock where you keep the items. When you disconnect and return to spawn, the items remain the same. But those items that were in the world disappear..

I first test all the plugins on my computer, then I upload them to the host.

**Comment by tastybento** [comment]
Okay, do you see the problem if you only run Bentobox on your computer and no other plugins.
